name: Bug
description: Report a bug with Funker Selector.
labels: ["Bug", "Awaiting Review"]
title: "Bug: "
body:
  - type: input
    attributes:
      label: Version
      description: What version of Friday Night Funkin' are you using?
      placeholder: ex. 0.4.1
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: Have you checked the Issues/Discussions to see if this hasn't been reported yet?
        - label: Have you tried reinstalling the mod?
        - label: Have you tried disabling every mod except Funker Selector?
        - label: Have you tried reproducing this issue on a fresh install of FNF?

  - type: markdown
    attributes:
      value: "## Describe the bug in detail."

  - type: markdown
    attributes:
      value: "### Please provide as many details as you can! I cannot read your mind."

  - type: textarea
    attributes:
      label: Context (Provide images, videos, etc.)