name: Bug
description: Report a bug with Funker Selector.
labels: ["Bug"]
title: "Bug: "
body:
  - type: input
    attributes:
      label: Version
      description: What version of Friday Night Funkin' are you using?
      placeholder: ex. 0.4.1
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: Have you checked the Issues/Discussions to see if this hasn't been reported yet?
        - label: Have you tried reinstalling the mod?
        - label: Is this a genuine issue with Funker Selector and not a side-effect of another mod you have installed?

  - type: markdown
    attributes:
      value: "## Describe the bug in detail."

  - type: markdown
    attributes:
      value: "### Provide as many details as you can!"

  - type: textarea
    attributes:
      label: Context (Provide images, videos, etc.)