name: Bug Report
description: Report a bug with Funker Selector.
labels: ["status: pending triage", "type: minor bug"]
title: "Bug Report: "
body:
  - type: input
    attributes:
      label: Version
      description: What version of Funker Selector are you using?
      placeholder: ex. 2.1.0
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: Have you checked the Issues/Discussions to see if this hasn't been reported yet?
        - label: Have you tried reproducing this issue on a fresh install of FNF?

  - type: markdown
    attributes:
      value: "## Describe the bug in detail."

  - type: markdown
    attributes:
      value: "### Please provide as many details as you can! I cannot read your mind."

  - type: textarea
    attributes:
      label: Context (Provide images, videos, etc.)
